/*
 Some components from jQuery UI | https://github.com/jquery/jquery-ui | MIT License
*/
(function(p){var w=window.AmazonUIPageJS||window.P,y=w._namespace||w.attributeErrors,h=y?y("AmazonUICalendar","AmazonUI"):w;h.guardFatal?h.guardFatal(p)(h,window):h.execute(function(){p(h,window)})})(function(p,w,y){p.when("A").register("a-calendar-utils",function(h){function g(a,b){b=a.getFullYear?a.getMonth()+1:b;a=a.getFullYear?a.getFullYear():a;return n(a,b+1,0).getDate()}function n(a,b,e){var c=null;a&&(c=a.getFullYear?new Date(a.getTime()):void 0!==a.year&&void 0!==a.month&&void 0!==a.day?new Date(a.year,
a.month-1,a.day):new Date(a,b-1,e));return c}function f(a){var b=a.match(/[.\/\-\s].*?/);a=a.split(/\W+/);if(!b||!a||0===a.length)throw Error("Invalid date format.");return{separator:b,parts:a}}return{numDaysInMonth:g,newDate:n,add:function(a,b,e){if("d"===e||"w"===e)a.setDate(a.getDate()+b*("w"===e?7:1));else{var c=a.getFullYear()+("y"===e?b:0);b=a.getMonth()+("m"===e?b:0);a.setTime(n(c,b+1,Math.min(a.getDate(),g(c,b+1))).getTime())}return a},parseDate:function(a,b){b=f(b);a=a?a.split(b.separator):
[];var e=null;if(a.length===b.parts.length){var c=new Date;for(var d=c.getFullYear(),k=c.getDate(),q=c.getMonth(),u=0;u<b.parts.length;u++)switch(c=parseInt(a[u],10),b.parts[u]){case "dd":case "d":k=c;break;case "mm":case "m":q=c-1;break;case "yy":case "yyyy":d=100>c?40>c?2E3+c:1900+c:c}!isNaN(d)&&0<=q&&11>=q&&1<=k&&k<=g(d,q+1)&&(e=new Date(d,q,k,0,0,0))}return e},formatDate:function(a,b){b=f(b);a={d:a.getDate(),m:a.getMonth()+1,yy:a.getFullYear()%100,yyyy:a.getFullYear()};a.dd=(10>a.d?"0":"")+a.d;
a.mm=(10>a.m?"0":"")+a.m;a.yy=(10>a.yy?"0":"")+a.yy;for(var e=[],c=0,d=b.parts.length;c<d;c++)e.push(a[b.parts[c]]);return e.join(b.separator)}}});"use strict";p.register("a-calendar-template-default",function(){return{monthNames:"January February March April May June July August September October November December".split(" "),dayNamesShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),firstDay:0,currentFormat:"{{month}} {{year}}",genericStatus:"Show {{month}} {{year}}",dateFormat:"mm/dd/yyyy",dateFormatDescription:"Date with format m m/d d/y y y y"}});
"use strict";p.when("A","a-calendar-utils","a-calendar-template-default").register("a-calendar-renderer",function(h,g,n){function f(a){if(0!==arguments.length)return this.templateData=a||n,this}var a=h.$,b=f.prototype;b.notifyChange=function(a,c){for(var e=this,b=a.attributes,q=a.$container,u=[],v=g.newDate(b.viewedYear,b.viewedMonth,1),l=0;l<b.numViewMonths;l++){var m=v.getMonth()+1,r=v.getFullYear();u.push(e.renderMonth(b,r,m,0===l,l===b.numViewMonths-1));v=g.add(v,1,"m")}h.delay(function(){q.html(u.join(""));
e.notifyBlacklistChange(a);c&&c();h.trigger("a:calendar:change:"+a.attributes.id)},0)};b.renderMonth=function(a,c,b,k,q){var e=this.templateData,d=g.numDaysInMonth(c,b),l=e.firstDay,m=g.newDate(c,b,1).getDay(),r=g.newDate(c,b,1).getTime(),f=g.newDate(c,b+1,0).getTime(),h=a.minDate?a.minDate.getTime():null,n=a.maxDate?a.maxDate.getTime():null,t=g.newDate(c,b,1),p=(m-l+7)%7;m=42-p-d;var w=a.selectedDate?a.selectedDate.getTime():null;g.add(t,-p,"d");l=[];for(var x=0;x<p;x++)l.push(this.renderDayOutsideMonth(t)),
g.add(t,1,"d");for(p=0;p<d;p++)x=t.getTime(),l.push(this.renderDay(t,a.selectedDate&&x===w,n&&x>n||h&&x<h,a.onRenderDayClass)),g.add(t,1,"d");for(a=0;a<m;a++)l.push(this.renderDayOutsideMonth(t)),g.add(t,1,"d");for(a=1;a<=l.length;a++)t=a-1,1===a?l[t]="\x3ctr\x3e"+l[t]:a===l.length?l[t]+="\x3c/tr\x3e":0===a%7&&(l[t]+="\x3c/tr\x3e\x3ctr\x3e");q=this.renderMonthHeader(c,b,k&&(!h||r>h),q&&(!n||f<n));r=this.renderDayHeader();f=e.currentFormat;f=f.replace("{{month}}",e.monthNames[(b-1+12)%12]).replace("{{year}}",
c);c=["\x3cdiv class\x3d'a-cal-month-container",k?" a-cal-month-container-first":"","'\x3e",q,"\x3ctable class\x3d'a-cal-month-table' summary\x3d'",f,"'\x3e",r,"\x3ctbody class\x3d'a-cal-days'\x3e"].concat(l);c.push("\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e");return c.join("")};b.renderDay=function(a,c,b,k){var e=a.getTime();k=["a-cal-d"," ",c?"a-cal-select ":"",b?"a-cal-outbound ":"",k?k.call(this,a)+" ":"","a-cal-d-",e];return["\x3ctd class\x3d'"].concat(k).concat(["' data-timestamp\x3d'",e,"'\x3e\x3ca href\x3d'javascript:void(0)' class\x3d'a-declarative a-cal-date-anchor' data-action\x3d'a-cal-select-date' aria-disabled\x3d'",
b?"true":"false","' aria-selected\x3d'",c?"true":"false","'\x3e",a.getDate(),"\x3c/a\x3e\x3c/td\x3e"]).join("")};b.renderDayOutsideMonth=function(a){return["\x3ctd class\x3d'a-cal-na a-cal-d-",a.getTime(),"'\x3e",this.templateData.dayOutsideMonth,"\x3c/td\x3e"].join("")};b.renderDayHeader=function(){for(var a=this.templateData,b=[],d=0;7>d;d++){var k=(d+a.firstDay)%7;b.push("\x3cth class\x3d'a-cal-day-label'\x3e");b.push(a.dayNamesShort[k]);b.push("\x3c/th\x3e")}a=["\x3cthead class\x3d'a-cal-labels'\x3e\x3ctr\x3e"].concat(b);
a.push("\x3c/tr\x3e\x3c/thead\x3e");return a.join("")};b.renderMonthHeader=function(a,b,d,k){var c=this.templateData,e=c.monthNames[(b-1+12)%12],g=c.monthNames[(b+12)%12],l=1===b?a-1:a,m=12===b?a+1:a,r=c.genericStatus,f=c.genericStatus,h=c.currentFormat;r=r.replace("{{month}}",c.monthNames[(b-2+12)%12]).replace("{{year}}",l);f=f.replace("{{month}}",g).replace("{{year}}",m);h=h.replace("{{month}}",e).replace("{{year}}",a);a=d?["\x3ca class\x3d'a-declarative a-cal-paginate-prev' data-action\x3d'a-cal-prev-month' href\x3d'javascript:void(0)' role\x3d'button'\x3e\x3cspan class\x3d'a-offscreen'\x3e",
r,"\x3c/span\x3e\x3ci class\x3d'a-icon a-icon-previous'\x3e\x3c/i\x3e\x3c/a\x3e"].join(""):"";k=k?["\x3ca class\x3d'a-declarative a-cal-paginate-next' data-action\x3d'a-cal-next-month' href\x3d'javascript:void(0)' role\x3d'button'\x3e\x3cspan class\x3d'a-offscreen'\x3e",f,"\x3c/span\x3e\x3ci class\x3d'a-icon a-icon-next'\x3e\x3c/i\x3e\x3c/a\x3e"].join(""):"";return["\x3cdiv class\x3d'a-row a-cal-month-row'\x3e\x3cdiv class\x3d'a-column a-span2'\x3e",a,"\x3c/div\x3e\x3cdiv class\x3d'a-column a-span8 a-text-center'\x3e\x3ch4 class\x3d'a-cal-month-header' tabindex\x3d'0'\x3e",
h,"\x3c/h4\x3e\x3c/div\x3e\x3cdiv class\x3d'a-column a-span2 a-span-last'\x3e",k,"\x3c/div\x3e\x3c/div\x3e"].join("")};b.notifyInputChange=function(a){var b=a.attributes.$inputContainer,d=a.attributes.calInput;if(b){a=a.attributes.selectedDate;b.find(".a-cal-input");if(a){var e=a.getMonth()+1;var q=a.getDate();var u=a.getFullYear()}b.find(".a-cal-select-month").val(e);b.find(".a-cal-select-day").val(q);b.find(".a-cal-select-year").val(u);d&&d.setDate(a)}};b.notifyDaySelection=function(a,b,d){a=a.$container.find(".a-cal-d.a-cal-d-"+
b.getTime());b=a.find("a");a.toggleClass("a-cal-select",d);b.attr("aria-selected",d)};b.notifyBlacklistChange=function(b){var c=b.$container,d=b.attributes.dateBlacklisted;d?c.find(".a-cal-d").each(function(b,c){b=a(c);var q=d(new Date(b.data("timestamp")));b.attr("aria-disabled",function(){return q?"true":"false"}).toggleClass("a-cal-inactive",q)}):c.find(".a-cal-d").removeClass("a-cal-inactive")};return f});"use strict";p.when("A","a-calendar-utils","a-calendar-renderer-instance","a-calendar-input").register("a-calendar",
function(h,g,n,f){function a(a,b){if(0!==arguments.length){b=b||{};this.$container=a;this.observer=b.observer||n;var c=this.attributes={numViewMonths:1};h.extend(c,b);c.selectedDate=g.newDate(c.selectedDate);c.minDate=g.newDate(c.minDate);c.maxDate=g.newDate(c.maxDate);var d=this.attributes.selectedDate||new Date;c.hasOwnProperty("viewedMonth")||(c.viewedMonth=d.getMonth()+1);c.hasOwnProperty("viewedYear")||(c.viewedYear=d.getFullYear());d=this.getTemplateData();if(c.$inputContainer&&d){var k=c.$inputContainer.find(".a-cal-input");
k.attr("aria-label",d.dateFormatDescription);c.calInput=new f(k,this,d.dateFormat)}c.id||(c.id=++e);this.observer.notifyChange(this);this.observer.notifyInputChange(this);return this}}var b=h.$,e=0,c=a.prototype;c.getTemplateData=function(){return this.observer?this.observer.templateData:null};c.selectDate=function(a,b,c){var d=this.attributes;if(!d.disabled){var e=g.newDate(a,b,c);if(!e||!isNaN(e.getFullYear())){var f=d.dateBlacklisted,m=d.minDate,r=d.maxDate;e&&(f&&f(a,b,c)||m&&e.getTime()<m.getTime()||
r&&e.getTime()>r.getTime())?d.onSelectInactiveDate&&d.onSelectInactiveDate.call(this,a,b,c):(f=this.observer,m=g.newDate(d.selectedDate),d.selectedDate=e,m&&f.notifyDaySelection(this,m,!1),d.selectedDate&&f.notifyDaySelection(this,d.selectedDate,!0),d.onSelectDate&&d.onSelectDate.call(this,a,b,c),d.selectedDate&&(a=d.viewedYear,b=d.viewedMonth,e=d.numViewMonths,c=(new Date(a,b-1,1)).getTime(),a=(new Date(a,b-1+e,0)).getTime(),b=d.selectedDate.getTime(),b<c||b>a)&&(this.changeViewedYear(d.selectedDate.getFullYear()),
this.changeViewedMonth(d.selectedDate.getMonth()+1)),this.observer.notifyInputChange(this))}}};c.changeViewedMonth=function(a,c){var d=this,e=d.attributes,f=d.$container;if(!e.disabled){var h=e.minDate,m=e.maxDate,r=e.viewedYear,k=g.newDate(r,a,1);r=g.newDate(r,a+1,0);h&&r.getTime()<h.getTime()||m&&k.getTime()>m.getTime()?e.onChangeViewedMonthFail&&e.onChangeViewedMonthFail.call(d,a):(e.viewedMonth=k.getMonth()+1,e.viewedYear=k.getFullYear(),d.observer.notifyChange(d,function(){e.onChangeViewedMonth&&
e.onChangeViewedMonth.call(d,a);"next"===c&&f.find(b(".a-cal-paginate-next")).focus();"previous"===c&&f.find(b(".a-cal-paginate-prev")).focus()}))}};c.changeViewedYear=function(a){var b=this,c=b.attributes;if(!c.disabled){var d=c.minDate,e=c.maxDate,f=c.viewedMonth,m=g.newDate(a,f,1);f=g.newDate(a,f+1,0);d&&f.getTime()<d.getTime()||e&&m.getTime()>e.getTime()?c.onChangeViewedYearFail&&c.onChangeViewedYearFail.call(b,a):(c.viewedMonth=m.getMonth()+1,c.viewedYear=m.getFullYear(),b.observer.notifyChange(b,
function(){c.onChangeViewedYear&&c.onChangeViewedYear.call(b,a)}))}};c.changeDateBlacklisted=function(a){this.attributes.disabled||(this.attributes.dateBlacklisted=a,this.observer.notifyBlacklistChange(this),this.attributes.onChangeDateBlacklisted&&this.attributes.onChangeDateBlacklisted.call(this,a))};c.setDisabled=function(a){this.attributes.disabled=a};return a});"use strict";p.when("A","a-calendar","a-calendar-renderer-instance","a-popover","ready").register("a-calendar-framework",function(h,
g,n,f){function a(a,b){a.jquery||(a=v(a));b=new g(a,b);l[b.attributes.id]=b;a.data("a-cal-id",b.attributes.id).addClass("a-cal-calendar-container").removeClass("a-cal-static");return b}function b(b,c){c=h.extend({activate:"onclick"},c||{});c=a(v("\x3cdiv /\x3e"),c);b.data("a-cal-id",c.attributes.id).data("a-cal-popover",!0).removeClass("a-cal-static");return c}function e(a,c){c=c||{};c.$inputContainer=a;c=b(a.find(".a-cal-input"),c);a.find(".a-cal-input-container").removeClass("a-hidden");a.find(".a-cal-dropdown-container").addClass("a-hidden").attr("aria-hidden",
"true");a.data("a-cal-id",c.attributes.id).data("a-cal-input",!0).addClass("a-cal-calendar-container").removeClass("a-cal-static");return c}function c(b,c){c=c||{};c.$inputContainer=b;c=a(v("\x3cdiv class\x3d'a-row a-cal-calendar-container' /\x3e"),c);b.append(c.$container);b.find(".a-cal-dropdown-container").addClass("a-hidden").attr("aria-hidden","true");b.data("a-cal-id",c.attributes.id).data("a-cal-input",!0).addClass("a-cal-calendar-container").removeClass("a-cal-static");return c}function d(a){a.jquery||
(a=v(a));var b=a.data("a-cal-renderer-instance")||"a-calendar-renderer-instance";"a-calendar-renderer-instance"===b?k(a,n):p.when(b).execute(function(b){k(a,b)})}function k(d,f){var m=d.data("a-cal-attributes")||{},g=d.data("a-cal-popover"),r=d.data("a-cal-input"),k=d.data("a-cal-inline");f=h.extend({observer:f},m);r?k?c(d,f):e(d,f):g?b(d,f):a(d,f)}function q(){v(".a-cal-static").each(function(){d(v(this))})}function u(a){a.jquery||(a=v(a));if(a.length){var b=a.closest(".a-cal-calendar-container");
b=b.length?l[b.data("a-cal-id")]:l[a.data("a-cal-id")]}return b}var v=h.$,l={};h.on("a:pageUpdate ready",q);h.declarative("a-cal-input",["click","keyup"],function(a){if(("keyup"===a.type&&a.$event.keyCode===h.constants.keycodes.ENTER||"click"===a.type)&&!f.get(a.$target)){var b=a.$target.data("a-cal-id");b=l[b];f.create(a.$target,{activate:"onclick",focusWhenShown:!0,width:"auto",padding:"none",position:b.attributes.position?b.attributes.position:"triggerBottom",closeButton:!1,popoverArrow:!1,dataStrategy:"inline"}).update({content:b.$container.addClass("a-cal-in-popover")}).show()}});
return{create:a,createWithPopover:b,createWithInput:e,createWithInputInline:c,createAll:q,get:u,getById:function(a){return l[a]},remove:function(a){var b=u(a);if(b){var c=b.attributes.$inputContainer;b.$container.remove();delete l[b.attributes.id];a.data("a-cal-popover")&&f.remove(a);c&&(a=c.find(".a-popover-trigger"),a.data("a-cal-popover")&&f.remove(a))}}}});"use strict";p.when("A","a-calendar-framework","a-popover").register("a-calendar-handler",function(h,g,n){var f=h.$;h.declarative("a-cal-select-date",
["click"],function(a){var b=a.$target;if(a=g.get(b))b=new Date(b.parent().data("timestamp")||b.data("timestamp")),a.selectDate(b),a.attributes.$inputContainer&&(a=n.get(a.attributes.$inputContainer.find(".a-cal-input")))&&a.hide()});h.declarative("a-cal-dropdown-select",["change"],function(a){if(a=g.get(a.$target)){var b=a.attributes.$inputContainer;if(b){var e=b.find(".a-cal-select-year").val(),c=b.find(".a-cal-select-month").val();b=b.find(".a-cal-select-day").val();e&&c&&b&&a.selectDate(e,c,b)}}});
h.declarative("a-cal-prev-month",["click"],function(a){(a=g.get(a.$target))&&a.changeViewedMonth(a.attributes.viewedMonth-1,"previous")});h.declarative("a-cal-next-month",["click"],function(a){(a=g.get(a.$target))&&a.changeViewedMonth(a.attributes.viewedMonth+1,"next")});f(document).delegate(".a-icon-calendar","click",function(a){a.stopImmediatePropagation();f(a.target).parent().siblings(".a-cal-input").focus().click();f("html").hasClass("a-ie8")&&f(a.target).addClass("a-hey-ie8").removeClass("a-hey-ie8")});
f(document).delegate(".a-cal-input","focusin",function(a){f(a.target).siblings(".a-icon-calendar").addClass("a-icon-calendar-focus")}).delegate(".a-cal-input","focusout",function(a){f(a.target).siblings(".a-icon-calendar").removeClass("a-icon-calendar-focus")})});"use strict";p.when("A","a-calendar-renderer","a-calendar-template-default").register("a-calendar-renderer-instance",function(h,g,n){return new g(n)});"use strict";p.when("A","a-calendar-utils").register("a-calendar-input",function(h,g){function n(f,
a,b){var e=this;e.$input=f;e.format=b;e.curDate=g.parseDate(f.val(),b);e.$input.bind("keyup change",function(){e.curDate=g.parseDate(f.val(),b);a.selectDate(e.curDate)}).bind("focusout",function(){e.setDate(a.attributes.selectedDate,!0)}).bind("keydown",function(a){a.keyCode===h.constants.keycodes.ENTER&&a.preventDefault()})}n.prototype.setDate=function(f,a){var b=this.curDate,e=b instanceof Date,c=f instanceof Date,d=e&&c;if(!f||c)if(e=!d&&(e||c),d&&b.getTime()!==f.getTime()||d&&!0===a||e)f=(this.curDate=
f)?g.formatDate(f,this.format):null,this.$input.val(f)};return n})});